blogs/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^news/$', views.NewsListView.as_view(), name='news'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsDetailView.as_view(), name='news_detail'),

    url(r'^persons/$', views.PersonsMixedListView.as_view(), name='persons'),
    url(
        r'^persons/(?P<pr_type>\w+)/$',
        views.PersonsOneTypeListView.as_view(),
        name='persons_type_interviews'
    ),
    url(
        r'^interview/(?P<id>[0-9]+)/$',
        views.InterviewPersonDetailView.as_view(),
        name='interview_person_detail'
    ),
    url(
        r'^persons/(?P<pr_type>\w+)/(?P<id>[0-9]+)/$',
        views.PersonPageDetailView.as_view(),
        name='person_page'
    ),
    url(r'^video/$', views.VideoListView.as_view(), name='video'),

    url(r'^tags/get/$', views.tags_get, name='tags_get'),

    url(r'^tribune/$', views.TribuneListView.as_view(), name='tribune'),
    url(r'^experts/$', views.ExpertsListView.as_view(), name='experts'),
    url(r'^forecast/$', views.ForecastListView.as_view(), name='foreacst'),
    url(r'^initiative/$', views.DiscussListView.as_view(), name='discuss'),
    url(r'^rating/set/$', views.rating_view, name='rating_set'),

    url(r'^audio/$', views.AudioListView.as_view(), name='audio')
]

bobsoccer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views
from django.views.generic import TemplateView

from users.views import ckeditor_image_upload_view, ckeditor_image_browse_view
from common.views import index

urlpatterns = [
    url(r'^users/success_signup/$', TemplateView.as_view(template_name='success_signup.html'), name='success_signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha', include('captcha.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('users.urls', namespace='accounts')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^forum/', include('talks.urls', namespace='forum')),
    url(r'^poll/', include('polls.urls', namespace='polls')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
    url(r'^payment/', include('transaction.urls', namespace='transaction')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^ckeditor/upload/$', ckeditor_image_upload_view, name='ckeditor_upload'),
    url(r'^ckeditor/browse/$', ckeditor_image_browse_view, name='ckeditor_browse'),
    url(r'^', include('common.urls', namespace='common'))
]

if settings.DEBUG:
    urlpatterns += [
            url(r'^static/(?P<path>.*)$', views.serve),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shop_view, name='base'),
    url(r'^cart/$', views.cart_view, name='cart'),
    url(r'^cart/add/$', views.ajax_cart_add, name='cart_add'),
    url(r'^cart/remove$', views.ajax_cart_remove, name='cart_remove'),
]

users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^items/$', views.user_items_view, name='user_items'),
    url(r'^items/get/$', views.get_user_items, name='items_get'),
    url(r'^items/send/$', views.gift_send, name='gift_send'),

    url(r'^friend/request/$', views.send_friend_request, name='friend_request'),

    url(r'^(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(),
        name='profile'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.ProfileUpdateView.as_view(),
        name='profile_update'),

    url(r'^(?P<pk>[0-9]+)/mail/$', views.ProfileMailView.as_view(),
        name='profile_mail'),
    url(r'^(?P<pk>[0-9]+)/messages/get/$', views.MessagesView.as_view(), name='messages_get'),
    url(r'^(?P<pk>[0-9]+)/messages/create/$', views.messages_create, name='messages_create'),

    url(r'^(?P<pk>[0-9]+)/messages/ignore/$', views.add_to_ignore, name='add_to_ignore'),

    url(r'^blog/create/$', views.article_create_view, name='article_create'),
    url(r'^(?P<pk>[0-9]+)/blog/$', views.article_list_view, name='article_list'),
    url(r'^blog/(?P<pk>[0-9]+)/update/$', views.article_update_view, name='article_update'),
    url(r'^(?P<pk>[0-9]+)/blog/(?P<article_id>[0-9]+)/$', views.article_detail_view, name='article_detail'),
    url(r'^blog/(?P<pk>[0-9]+)/delete/$', views.article_delete_view, name='article_delete'),
    url(r'^blog/(?P<pk>[0-9]+)/hide/$', views.article_hide_view, name='article_hide'),

    url(r'^(?P<pk>[0-9]+)/map/$', views.user_map, name='map'),

    url(r'^album/new/$', views.new_album, name='new_album'),

    url(r'^(?P<pk>[0-9]+)/photos/$', views.user_photos_all, name='photos_all'),

    url(r'^(?P<pk>[0-9]+)/album/gallery/$', views.gallery_photo, name='gallery_photo'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/gallery/$', views.gallery_photo, name='gallery_album'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/$', views.user_photo, name='photos'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/$', views.user_photo, name='photos_album'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/remove/$', views.album_remove, name='photos_remove'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/remove/$', views.album_remove, name='album_remove'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/hide/$', views.hide_album, name='photos_hide'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/hide/$', views.hide_album, name='album_hide'),

    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/update/$', views.album_update, name='album_update'),

    url(r'^(?P<pk>[0-9]+)/coords/set/$', views.user_set_coords, name='set_coords'),

    url(r'^(?P<pk>[0-9]+)/photo/upload/$', views.user_upload_photo, name='upload_photos'),
    url(r'^(?P<pk>[0-9]+)/photo/(?P<album>[0-9])/upload/$', views.user_upload_photo, name='upload_photos_album'),
]

soccer/models.py
# -*- coding: utf-8 -*-


from __future__ import unicode_literals

from django.db import models
from django.db.models import Count
from django.utils.translation import ugettext as _


class Team(models.Model):
    name = models.CharField(_('Имя'), max_length=255)
    logo = models.ImageField(_('Логотип'), upload_to='team/logos/', null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Команда')
        verbose_name_plural = _('Команды')


class PersonObjects(models.QuerySet):
    def coaches(self, *args, **kwargs):
        kwargs['type'] = 'coach'
        return self.filter(*args, **kwargs)

    def players(self, *args, **kwargs):
        kwargs['type'] = 'player'
        return self.filter(*args, **kwargs)

    def specs(self, *args, **kwargs):
        kwargs['type'] = 'spec'
        return self.filter(*args, **kwargs)


class Person(models.Model):
    class TYPE:
        COACH = 'coach'
        PLAYER = 'player'
        SPEC = 'spec'
        _CHOICES = ((COACH, 'Тренер'),
                    (PLAYER, 'Игрок'),
                    (SPEC, 'Специалист'))

    name = models.CharField(_('Имя'), max_length=255)
    image = models.ImageField(_('Изображение'), upload_to='team/persons')
    type = models.CharField(
        _('Тип'),
        max_length=10,
        choices=TYPE._CHOICES,
        default=TYPE.PLAYER
    )
    info = models.TextField(_('Информация'))
    team = models.ForeignKey(Team, verbose_name=_('Команда'))

    objects = PersonObjects.as_manager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Персона')
        verbose_name_plural = _('Персоны')

    def authors(self):
        return self.articles.values('user__username').annotate(
            c=Count('user__username')).values('c', 'user__username')

blogs/views.py
# coding=utf-8
import json
from collections import defaultdict

from django.db.models import Max
from django.http import Http404
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic import ListView

from blogs.models import Article, Tag, ArticleRating
from soccer.models import Person


class NewsListView(ListView):
    model = Article
    paginate_by = 20
    template_name = 'blogs/article_list.html'

    def get_queryset(self):
        return Article.objects.news().order_by('-when_created')

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)
        context['article_type'] = u'Новости'
        return context


class ExpertsListView(ListView):
    def get_queryset(self):
        return Article.objects.experts().order_by('-when_created')

    def get_context_data(self, **kwargs):
        context = super(ExpertsListView, self).get_context_data(**kwargs)
        context['article_type'] = u'Экспертное мнение'
        return context


class TribuneListView(ListView):
    paginate_by = 20
    model = Article
    template_name = 'blogs/article_list.html'

    def get_queryset(self):
        return Article.objects.tribune().order_by('-when_created')

    def get_context_data(self, **kwargs):
        context = super(TribuneListView, self).get_context_data(**kwargs)
        context['article_type'] = u'Трибуна'
        return context


class ForecastListView(ListView):
    paginate_by = 20
    model = Article
    template_name = 'blogs/article_list.html'

    def get_queryset(self):
        return Article.objects.forecast().order_by('-when_created')

    def get_context_data(self, **kwargs):
        context = super(ForecastListView, self).get_context_data(**kwargs)
        context['article_type'] = u'Блог конкурса прогнозов'
        return context


class DiscussListView(ListView):
    paginate_by = 20
    model = Article
    template_name = 'blogs/article_list.html'

    def get_queryset(self):
        return Article.objects.discuss().order_by('-when_created')

    def get_context_data(self, **kwargs):
        context = super(DiscussListView, self).get_context_data(**kwargs)
        context['article_type'] = u'Инициативы / онлайн обсуждения'
        return context


class NewsDetailView(DetailView):
    model = Article
    slug_field = 'pk'


class PersonsMixedListView(ListView):
    model = Person
    template_name = 'blogs/persons.html'

    def get_queryset(self):
        return Person.objects.annotate(last_comment=Max(
            'articles__when_created')).order_by('-last_comment')

    def get_context_data(self, **kwargs):
        context = super(PersonsMixedListView, self).get_context_data(**kwargs)
        persons = defaultdict(list)
        limits = {Person.TYPE.COACH: 4,
                  Person.TYPE.PLAYER: 8,
                  Person.TYPE.SPEC: 4}
        for person in self.object_list.iterator():
            if person.type not in limits:
                continue
            if len(persons[person.type]) < limits[person.type]:
                persons[person.type].append(person)
            else:
                del limits[person.type]
            if not limits:
                break

        context['persons'] = persons
        types = {'coaches': Person.objects.coaches(),
                 'players': Person.objects.players(),
                 'specs': Person.objects.specs()}
        context['types'] = types
        return context


class PersonsOneTypeListView(PersonsMixedListView):
    paginate_by = 4
    template_name = 'blogs/persons_one_type.html'

    def get_queryset(self, *args, **kwargs):
        q = self.kwargs.get('pr_type')
        return Person.objects.filter(type=q).order_by(
            '-articles__when_created')


class InterviewPersonDetailView(DetailView):
    model = Article
    template_name = 'blogs/interview_person.html'
    pk_url_kwarg = 'id'

    def get_queryset(self, *args, **kwargs):
        return Article.objects.interview()


class VideoListView(ListView):
    template_name = 'blogs/video.html'
    model = Article
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.videos()

    def get_context_data(self, **kwargs):
        context = super(VideoListView, self).get_context_data(**kwargs)
        context['loop_times'] = range(1, 19)
        return context


class PersonPageDetailView(DetailView):
    model = Person
    template_name = 'blogs/person_page.html'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return Person.objects.filter(type=self.kwargs.get('pr_type'))

    def get_context_data(self, **kwargs):
        context = super(PersonPageDetailView, self).get_context_data(**kwargs)
        articles = self.object.articles.select_related('user')
        context['articles'] = articles
        return context


def tags_get(request):
    if request.method == 'POST' and request.is_ajax():
        q = request.POST.get('q')
        data = {
            'tags': list(Tag.objects.filter(name__istartswith=q).values_list('name', flat=True))
        }
        return JsonResponse(json.dumps(data))
    raise Http404()


def rating_view(request):
    if not (request.method == 'POST' and request.is_ajax()):
        raise Http404()

    try:
        article = Article.objects.get(pk=request.POST.get('article'))
    except Article.DoesNotExist:
        return HttpResponse('error')

    rate, created = ArticleRating.objects.get_or_create(user=request.user, article=article)
    rate.rate = request.POST.get('rate')
    rate.save()
    data = article.rating()
    data['count'] = article.ratings.count()

    return JsonResponse(json.dumps(data), safe=False)


class AudioListView(ListView):
    model = Article
    paginate_by = 20
    template_name = 'audio.html'

    def get_queryset(self):
        return Article.objects.audios().order_by('-when_created')

blogs/templates/blogs/_article_preview.html
{% load relativedate %}
<div class="comment">
    <div class="activity_score">
        <span class="when">
            {% if article.is_popular %}<span class="red_rating"></span>{% endif %}
            {% if article.is_commentable %}<span class="red_comment"></span>{% endif %}
                {{ article.when_created.date|reldate }}, {{ article.when_created.time }}
        </span>
        <div class="right_score">
            <span class="comments_score">{{ article.comments.count }}</span>/<span class="saw_score">{{ article.total_views }}</span>
        </div>
    </div>
    <a href="{% url 'accounts:article_detail' article.user.pk article.pk %}"><p>{{ article.title }}</p></a>
    <p>{{ article.announce }}</p>
</div>

blogs/templates/blogs/article_list.html
{% extends "base_template.html" %}
{% load staticfiles %}
{% load cache %}

{% block content-header %}
    {% include 'slider.html' %}
{% endblock %}
{#    здесь весь раздел новостей, надо раскоментить, а код одной статьи с коментами перенести#}

{% block content %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna">
            <div class="central_column">
                <p class="caption news_caption">{{ article_type }}</p>

            {% cache 100 articles_block %}
                <div class="news_block">
                    {% for object in object_list %}
                        <div class="comment">
                            <div class="activity_score">
                                <span class="activity_title"><a
                                        href="{% url 'accounts:article_detail' object.user.pk object.pk %}">{{ object.title|safe }}</a></span>
                                <div class="right_score">
                                    <span class="comments_score">{{ object.when_created }}</span><span
                                        class="saw_score">{{ object.total_views }}</span>
                                </div>
                            </div>
                            <div class="profile_tribuna">
                                <a href="#">
                                    <img src="{% static "img/lk_ava.png" %}" width="70px" alt="">
                                    <span class="nickname_tribuna">{{ object.user }}</span>
                                </a>
                            </div>
                            <div class="comment_right">
                                <p>{{ object.text|truncatechars_html:100|safe }}</p>
                            </div>
                        </div>
                    {% endfor %}
                    {% if is_paginated %}
                        {% include 'pagination.html' %}
                    {% endif %}
                    <div class="now_chat">
                        <p class="now_chat_title">Сейчас обсуждается:</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:08</a> Максим Митрофанов: Наибольшие опасения
                            сейчас вызывает транспортная логистика</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:07</a> Будогосский: программа работы одобрена, с
                            нашим судейством нужно что-то делать</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:07</a> Сергей Ольшанский: Слуцкому нужно больше
                            доверять Страндбергу, Траоре уже "поиграл"</p>
                    </div>
                </div>
            {% endcache %}

                <!-- <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#avtor" aria-controls="avtor" role="tab" data-toggle="tab">Авторские</a></li>
                    <li role="presentation"><a href="#istok" aria-controls="istok" role="tab" data-toggle="tab">Из источников</a></li>
                    <li role="presentation"><a href="#all" aria-controls="all" role="tab" data-toggle="tab">Все</a></li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="avtor">


                    </div>
                    <div role="tabpanel" class="tab-pane" id="istok">
                        <div class="comment">
                            <div class="activity_score">
                                <span class="when">Сегодня, 12:46</span>
                                <div class="right_score">
                                    <span class="comments_score">764</span>/<span class="saw_score">12314</span>
                                </div>
                            </div>
                            <a href="#"><p>Лодыгин: с "Ростовом" у меня была не одна ошибка, вся игра в целом не удалась</p></a>
                            <p>Вратарь "Зенита" Юрий Лодыгин признался, что в домашней встрече с...</p>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="all">
                        <div class="comment">
                            <div class="activity_score">
                                <span class="when">Сегодня, 12:46</span>
                                <div class="right_score">
                                    <span class="comments_score">764</span>/<span class="saw_score">12314</span>
                                </div>
                            </div>
                            <a href="#"><p>Лодыгин: с "Ростовом" у меня была не одна ошибка, вся игра в целом не удалась</p></a>

                        </div>
                    </div>
                </div> -->
            </div>
        </div>
    </div>



{% endblock content %}
{% block additional_scripts %}

    <script src="{% static 'js/jquery.barrating.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#rating_photo').barrating({
                theme: 'fontawesome-stars'
            });
        });
    </script>
{% endblock %}

blogs/templates/blogs/edit_buttons.html
{% load staticfiles %}
{% load permissions %}
{% if object.user == request.user %}
    <a href="{% url 'accounts:article_hide' object.pk %}" class="article_hide">
    {% if object.not_publish %}
        <img src="{% static "img/eye.png" %}" width="18px">
    {% else %}
        {# TODO: Изменить вид иконки при показанной статье #}
        <img src="{% static 'img/eye.png' %}" alt="">
    {% endif %}
    </a>
    <a href="{% url 'accounts:article_update' pk=object.pk %}"> <img src="{% static "img/pen.png" %}" width="15px"></a>
    <a href="{% url 'accounts:article_delete' object.pk %}"> <img src="{% static "img/dell.png" %}" width="15px"></a>
{% else %}
    {% if request.user|has_perm:'blogs.change_article' %}
        <a href="{% url 'accounts:article_hide' object.pk %}" class="article_hide"><img src="{% static "img/eye.png" %}" width="18px"></a>
        <a href="{% url 'accounts:article_update' object.pk %}"> <img src="{% static "img/pen.png" %}" width="15px"></a>
    {% endif %}
    {% if request.user|has_perm:'blogs.delete_article' %}
        <a href="{% url 'accounts:article_delete' object.pk %}"> <img src="{% static "img/dell.png" %}" width="15px"></a>
    {% endif %}
{% endif %}

blogs/templates/blogs/person_page.html
{% extends "base_template.html" %}
{% load staticfiles %}

{%block additional_links %}
    <link rel="stylesheet" href="{% static "css/fontawesome-stars.css" %}">
{% endblock %}

{% block content-header %}
    {% include 'slider.html'%}
{% endblock %}

{% block content %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna interview">
            <div class="central_column">
                <p class="caption news_caption interview_caption">Интервью</p>
                <div class="news_block">
                    <div class="interview_full">
                        <div class="interview_razdel_player">
                            <img width="120px" height="120px" src="{{ person.image.url }}" alt="" class="interview_razdel_player_logo">
                            <div class="interview_razdel_player_team">
                                <p>{{ person.get_type_display }}</p>
                                <img width="90px" height="90px" src="{{ person.team.logo.url }}" alt="">
                            </div>
                            <div class="interview_razdel_player_text">
                                <p class="interview_razdel_name">{{ person.name }}</p>
                                <p>{{ person.info }}</p>
                            </div>
                        </div>
                        {% for article in articles %}
                        <div class="activity_score">
                            <a href="{% url 'accounts:article_detail' article.user.id article.id %}" class="activity_title_other">{{ person.name }}</a>
                            <div class="right_score">
                                <span class="comments_score">{{ article.when_created|date:"j E H:i" }}</span>
                            </div>
                        </div>
                        <div class="interview_razdel_comment">
                            <div class="interview_razdel_comment_left">
                                <img src="{% static 'img/interview/ava.png' %}" alt="">
                                <a href="#">{{ article.user.username }}</a>
                            </div>

                                <p>{{ article.title }}</p>
                                <div>{{ article.anounce }}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{##}
{% block additional_scripts %}
<script src="{% static 'js/jquery.barrating.min.js' %}"></script>
<script type="text/javascript">
   $(function() {
      $('#rating_photo').barrating({
        theme: 'fontawesome-stars'
      });
   });
</script>
{% endblock %}

blogs/templates/blogs/persons.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block content-header %}
    {% include 'slider.html' %}
{% endblock %}

{% block content %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna interview">
            <div class="central_column">
                <p class="caption news_caption">Интервью</p>
                <div class="news_block">
                    {% if types.players %}
                        <div class="interview_people">
                            <div class="activity_score">
                                <div class="activity_title_other">
                                    <span>Игроки</span>
                                </div>
                            </div>
                            <div class="people_ul clearfix">
                                <ul class="person-block-wrap">
                                    {% for i in types.players %}
                                        <li>
                                            <div class="person-block">
                                                <div class="person-img">
                                                    <img src="{{ i.image.url }}" alt="">
                                                    <div class="person-team">
                                                        <img src="{% static 'img/loko.png' %}" alt="">
                                                    </div>
                                                </div>
                                                <a href="{% url 'blogs:person_page' 'player' i.id %}">{{ i.name }}</a>
                                                <div>
                                                    дата <br>
                                                    {% for author in i.authors %}
                                                        <a class="user-int" href="#">{{ author.user__username }}</a><span>-{{ author.c }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>

                                <a href="{% url 'blogs:persons_type_interviews' 'player' %}" class="people_ul_button">Все</a>
                            </div>

                        </div>
                    {% endif %}
                    {% if types.coaches %}
                        <div class="interview_people">
                            <div class="activity_score">
                                <div class="activity_title_other">
                                    <span>Тренеры</span>
                                </div>
                            </div>
                            <div class="people_ul clearfix">
                                <ul class="person-block-wrap">
                                    {% for i in types.coaches %}
                                        <li>
                                            <div class="person-block">
                                                <div class="person-img">
                                                    <img src="{{ i.image.url }}" alt="">
                                                    <div class="person-team">
                                                        <img src="{% static 'img/loko.png' %}" alt="">
                                                    </div>
                                                </div>
                                                <a href="{% url 'blogs:person_page' 'coach' i.id %}">{{ i.name }}</a>
                                                <div>
                                                    дата <br>
                                                    {% for author in i.authors %}
                                                        <a class="user-int" href="#">{{ author.user__username }}</a><span>-{{ author.c }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>

                                <a href="{% url 'blogs:persons_type_interviews' 'coach' %}" class="people_ul_button">Все</a>
                            </div>
                        </div>
                    {% endif %}
                    {% if types.specs %}
                        <div class="interview_people">
                            <div class="activity_score">
                                <div class="activity_title_other">
                                    <span>Специалисты</span>
                                </div>
                            </div>
                            <div class="people_ul clearfix">
                                <ul class="person-block-wrap">
                                    {% for i in types.specs %}
                                        <li>
                                            <div class="person-block">
                                                <div class="person-img">
                                                    <img src="{{ i.image.url }}" alt="">
                                                    <div class="person-team">
                                                        <img src="{% static 'img/loko.png' %}" alt="">
                                                    </div>
                                                </div>
                                                <a href="{% url 'blogs:person_page' 'spec' i.id %}">{{ i.name }}</a>
                                                <div>
                                                    дата <br>
                                                    {% for author in i.authors %}
                                                        <a class="user-int" href="#">{{ author.user__username }}</a><span>-{{ author.c }}</span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>

                                <a href="{% url 'blogs:persons_type_interviews' 'spec' %}" class="people_ul_button">Все</a>
                            </div>
                        </div>
                    {% endif %}

                    <div class="now_chat">
                        <p class="now_chat_title">Сейчас обсуждается:</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:08</a> Максим Митрофанов: Наибольшие опасения
                            сейчас вызывает транспортная логистика</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:07</a> Будогосский: программа работы одобрена, с
                            нашим судейством нужно что-то делать</p>
                        <p class="now_chat_text"><a href="#">Сегодня 14:07</a> Сергей Ольшанский: Слуцкому нужно больше
                            доверять Страндбергу, Траоре уже "поиграл"</p>
                    </div>


                </div>

            </div>
        </div>
    </div>
{% endblock content %}

blogs/templates/blogs/persons_type_partly.html
{% load staticfiles %}

<div class="people_ul clear_fix">
    <ul>
        {% for person in persons_list %}
            <li><img src="{{ person.image.url }}" alt=""><a href="{% url 'blogs:person_page' person.type person.id %}">{{ person.name }}</a> </li>
        {% endfor %}
    </ul>
    <a href="{% url 'blogs:persons_type_interviews' pr_type=person_type %}" class="people_ul_button">Все</a>
</div>