bobsoccer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views
from django.views.generic import TemplateView

from users.views import ckeditor_image_upload_view, ckeditor_image_browse_view
from common.views import index

urlpatterns = [
    url(r'^users/success_signup/$', TemplateView.as_view(template_name='success_signup.html'), name='success_signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha', include('captcha.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('users.urls', namespace='accounts')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^forum/', include('talks.urls', namespace='forum')),
    url(r'^poll/', include('polls.urls', namespace='polls')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
    url(r'^payment/', include('transaction.urls', namespace='transaction')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^ckeditor/upload/$', ckeditor_image_upload_view, name='ckeditor_upload'),
    url(r'^ckeditor/browse/$', ckeditor_image_browse_view, name='ckeditor_browse'),
    url(r'^', include('common.urls', namespace='common'))
]

if settings.DEBUG:
    urlpatterns += [
            url(r'^static/(?P<path>.*)$', views.serve),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shop_view, name='base'),
    url(r'^cart/$', views.cart_view, name='cart'),
    url(r'^cart/add/$', views.ajax_cart_add, name='cart_add'),
    url(r'^cart/remove$', views.ajax_cart_remove, name='cart_remove'),
]

users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^items/$', views.user_items_view, name='user_items'),
    url(r'^items/get/$', views.get_user_items, name='items_get'),
    url(r'^items/send/$', views.gift_send, name='gift_send'),

    url(r'^friend/request/$', views.send_friend_request, name='friend_request'),

    url(r'^(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(),
        name='profile'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.ProfileUpdateView.as_view(),
        name='profile_update'),

    url(r'^(?P<pk>[0-9]+)/mail/$', views.ProfileMailView.as_view(),
        name='profile_mail'),
    url(r'^(?P<pk>[0-9]+)/messages/get/$', views.MessagesView.as_view(), name='messages_get'),
    url(r'^(?P<pk>[0-9]+)/messages/create/$', views.messages_create, name='messages_create'),

    url(r'^(?P<pk>[0-9]+)/messages/ignore/$', views.add_to_ignore, name='add_to_ignore'),

    url(r'^blog/create/$', views.article_create_view, name='article_create'),
    url(r'^(?P<pk>[0-9]+)/blog/$', views.article_list_view, name='article_list'),
    url(r'^blog/(?P<pk>[0-9]+)/update/$', views.article_update_view, name='article_update'),
    url(r'^(?P<pk>[0-9]+)/blog/(?P<article_id>[0-9]+)/$', views.article_detail_view, name='article_detail'),
    url(r'^blog/(?P<pk>[0-9]+)/delete/$', views.article_delete_view, name='article_delete'),
    url(r'^blog/(?P<pk>[0-9]+)/hide/$', views.article_hide_view, name='article_hide'),

    url(r'^(?P<pk>[0-9]+)/map/$', views.user_map, name='map'),

    url(r'^album/new/$', views.new_album, name='new_album'),

    url(r'^(?P<pk>[0-9]+)/photos/$', views.user_photos_all, name='photos_all'),

    url(r'^(?P<pk>[0-9]+)/album/gallery/$', views.gallery_photo, name='gallery_photo'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/gallery/$', views.gallery_photo, name='gallery_album'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/$', views.user_photo, name='photos'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/$', views.user_photo, name='photos_album'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/remove/$', views.album_remove, name='photos_remove'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/remove/$', views.album_remove, name='album_remove'),

    url(r'^(?P<pk>[0-9]+)/album/non_album/hide/$', views.hide_album, name='photos_hide'),
    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/hide/$', views.hide_album, name='album_hide'),

    url(r'^(?P<pk>[0-9]+)/album/(?P<album>[0-9])/update/$', views.album_update, name='album_update'),

    url(r'^(?P<pk>[0-9]+)/coords/set/$', views.user_set_coords, name='set_coords'),

    url(r'^(?P<pk>[0-9]+)/photo/upload/$', views.user_upload_photo, name='upload_photos'),
    url(r'^(?P<pk>[0-9]+)/photo/(?P<album>[0-9])/upload/$', views.user_upload_photo, name='upload_photos_album'),
]

users/views.py
# coding=utf-8

from allauth.account.views import SignupView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.http.response import JsonResponse, HttpResponse, \
    HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView

from blogs.models import Article, Audio
from bobsoccer.decorators import ajax_post_only
from common.utils import delete_cache
from polls.forms import poll_formset
from polls.models import Poll, PollVariant
from shop.models import Item
from talks.forms import CommentCreateForm
from .decorators import for_current_user_or_perm, views_count, for_current_user
from .forms import ProfileUpdateForm, MessageCreateForm, ArticleForm, album_image_formset, AlbumForm
from .models import User, Message, UserLocation, AlbumImage, UserGift, UserItem, FriendRequest, Album


class MySignupView(SignupView):
    success_url = '/users/success_signup/'


class ProfileDetailView(DetailView):
    model = User
    template_name = 'lk.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['user'] = self.get_object()
        return context


class ProfileUpdateView(UpdateView):
    model = User
    template_name = 'account/signup.html'
    form_class = ProfileUpdateForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProfileUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['profile_update'] = True
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        if password:
            user.set_password(password)
        user.save()
        self.success_url = reverse('accounts:profile', kwargs={'pk': user.pk})
        return super(ProfileUpdateView, self).form_valid(form)


class ProfileMailView(View):
    template_name = 'messages/base.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class MessagesView(View):
    names = {
        'inbox': u'Входящие',
        'spam': u'Спам',
        'sent': u'Отправленные',
        'friends': u'Друзья',
        'ignores': u'Игнорируемые',
        'contacts': u'Контакты'
    }
    template_name = ''
    context = {}

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            block = request.POST.get('block', 'messages')
            func = self.__getattribute__(block)
            if func:
                func(request)

            return render(request, self.template_name, self.context)

        raise Http404()

    def messages(self, request):
        messages_type = request.POST.get('type', 'inbox')
        func = getattr(Message, 'get_%s_messages' % messages_type)

        self.context.update({
            'table_name': self.names[messages_type],
            'messages': func(request.user) if func else []
        })
        self.template_name = 'messages/list.html'

    def contacts(self, request):
        contacts_type = request.POST.get('type', 'contacts')
        func = getattr(request.user, 'get_%s' % contacts_type)
        contacts = func() if func() else []

        self.context.update({
            'table_name': self.names[contacts_type],
            'contacts': contacts
        })
        self.template_name = 'contacts/list.html'

    def write_message(self, request):
        re = request.POST.get('msg')
        if re:
            try:
                re = Message.objects.get(pk=re)
            except Message.DoesNotExist:
                pass

        self.context.update({
            'table_name': u'Новое сообщение',
            're': re
        })
        self.template_name = 'messages/create.html'

    def settings(self, request):
        self.context.update({
            'table_name': u'Настройки сообщений'
        })
        self.template_name = 'messages/settings.html'

    def message_detail(self, request):
        msg = request.POST.get('msg')
        ignore = False
        try:
            message = Message.objects.get(pk=msg)

            if message.user_from in request.user.ignore.all():
                ignore = True

        except Message.DoesNotExist:
            message = None

        self.context.update({
            'object': message,
            'ignore': ignore
        })
        self.template_name = 'messages/detail.html'


@login_required
@ajax_post_only
def messages_create(request, *args, **kwargs):
    form = MessageCreateForm(request.POST)
    response = {'success': False}
    if form.is_valid():
        message = form.save(commit=False)
        user_to = User.objects.get(username=form.cleaned_data['user_to'])
        message.user_from = request.user
        message.user_to = user_to
        message.save()
        response['success'] = True

    if form.errors:
        response.update(form.errors)
    return JsonResponse(response)


@ajax_post_only
def add_to_ignore(request, *args, **kwargs):
    action = request.POST.get('action', 'add')
    success = True

    try:
        user = User.objects.get(pk=request.POST.get('user'))
        if action == 'add':
            request.user.ignore.add(user)
        elif action == 'remove':
            request.user.ignore.remove(user)

    except User.DoesNotExist:
        success = False

    return JsonResponse({'success': success})


@ajax_post_only
def contacts_view(request, pk):
    return render(request, 'contacts/list.html', {
        'contacts': request.user.friends.all()})


@login_required
def article_create_view(request):
    form = ArticleForm(request.POST or None, initial={
        'when_created': timezone.now()
    })

    formset = poll_formset(request.POST or None)

    if form.is_valid():
        error = False
        article = form.save(commit=False)
        article.user = request.user
        article.video_cover = form.cleaned_data.get('video_cover')
        article.save()

        poll_title = form.cleaned_data.get('poll_title')
        poll = form.cleaned_data.get('poll')

        if poll:
            formset = poll_formset(request.POST)
            if formset.is_valid():

                poll, created = Poll.objects.update_or_create(
                    article=article, defaults={
                        'title': poll_title,
                        'is_multivariant': form.cleaned_data.get('is_multiple'),
                    }
                )

                variants = []
                for f in formset:
                    text = f.cleaned_data.get('text')
                    if not text:
                        continue

                    variants.append(PollVariant(text=text, poll=poll))

                if not poll_title and variants:
                    error = True
                    form.add_error('poll_title', u'Введите вопрос')

                elif len(variants) < 2:
                    error = True
                    form.add_error(None, u'Добавьте ответов к опросу')

                else:
                    PollVariant.objects.bulk_create(variants)
            else:
                error = True

        audio = form.cleaned_data.get('audio')
        if audio:
            data = {
                'article_id': article.id,
                'title': form.cleaned_data.get('audio_title'),
                'time': form.cleaned_data.get('audio_start'),
                'file': form.cleaned_data.get('audio_file')
            }
            Audio.objects.create(**data)

        if not error:
            delete_cache('articles_block')
            messages.add_message(request, messages.SUCCESS, "Статья создана!")
            return HttpResponseRedirect(reverse('accounts:profile',
                                                kwargs={'pk': request.user.pk}))
    return render(request, 'blogs/create.html', {
        'form': form, 'formset': formset
    })


def article_list_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    paginator = Paginator(user.articles.all(), 25)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    context = {
        'articles': articles,
        'user': user
    }
    if paginator.num_pages > 1:
        context['is_paginated'] = True

    return render(request, 'blogs/list.html', context)


@login_required
@for_current_user_or_perm('blogs.change_article', model=Article)
def article_update_view(request, obj, **kwargs):
    tags = ','.join(list(obj.tags.values_list('name', flat=True)))
    initial = {
        'tags': tags,
    }

    poll_initial = {}
    if obj.get_poll():
        initial.update({
            'poll_title': obj.poll.title,
            'is_multiple': obj.poll.is_multivariant,
            'poll': True
        })
        poll_initial = obj.poll.options.values('text')

    if obj.get_broadcast():
        initial.update({
            'audio_title': obj.audio.title,
            'audio_start': obj.audio.time,
            'audio_file': obj.audio.file,
            'audio': True
        })

    form = ArticleForm(
        instance=obj,
        initial=initial,

users/templates/photo/gallery_photo.html
{% extends 'account/profile_base.html' %}
{% load staticfiles %}
{% block tab_content %}
    <div id="rg-gallery" class="rg-gallery">
        <div class="rg-thumbs">
            <div class="es-carousel-wrapper">
                <div class="es-nav">
                    <span class="es-nav-prev">Previous</span>
                    <span class="es-nav-next">Next</span>
                </div>
                <div class="es-carousel">
                    <ul>
                        {% for image in images %}
                            <li {% if image.pk == current %}class="selected"{% endif %}>
                                <a href="#">
                                    <img src="{{ image.image.url }}"
                                         data-large="{{ image.image.url }}"
                                         alt="image02" data-description="{{ image.title }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <!-- End Elastislide Carousel Thumbnail Viewer -->
        </div><!-- rg-thumbs -->
    </div>

{% endblock %}
{% block additional_scripts %}
    {#    <script src="js/jquery-2-0-0.js"></script>#}
    {##}

    {#    <script src="js/bootstrap.min.js"></script>#}
    {#    <script src="js/script.js"></script>#}
    {#    <script src="js/jquery.bxslider.min.js"></script>#}

    <script type="text/javascript" src="{% static 'js/gallery_slider/jquery.tmpl.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/gallery_slider/jquery.easing.1.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/gallery_slider/jquery.elastislide.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/gallery_slider/gallery.js' %}"></script>
    <script src="{% static 'js/jquery.barrating.min.js' %}"></script>
    <script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">
        <div class="rg-image-wrapper">
            <div class="redact clearfix">
                <div class="pull-left rg-caption" style="display:none">
                    <p></p>
                </div>
                <div class="pull-right right-options">
                    <a href="#"><img src="{% static "img/eye.png" %}" width="18px"></a>
                    <a href="#"> <img src="{% static "img/pen.png" %}" width="15px"></a>
                    <a href="#"> <img src="{% static "img/dell.png" %}" width="15px"></a>
                </div>
            </div>
            <div class="rg-image"></div>
            <div class="rg-loading"></div>
            <div class="rg-caption-wrapper"></div>
            <div class="your_rate">
                <p>Ваша оценка: <span>нет</span></p>
                <p class="average_rate"> Средняя: <span>4</span> <span>(1 голос)</span></p>
                <select id="rating_photo">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
        </div>
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            setTimeout(function(){
                $('#rating_photo').barrating({
                        theme: 'fontawesome-stars'
                });
            }, 200);
        });
    </script>
{% endblock %}
{% block additional_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_gallery.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/elastislide.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/photo.css' %}"/>
{% endblock %}

users/templates/photo/new_album_photo.html
{% extends 'account/profile_base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block tab_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {%  bootstrap_field field %}
        {% endfor %}
        <button class="btn btn-success" type="submit">Сохранить</button>
    </form>
{% endblock %}

users/templates/photo/user_photo.html
{% extends 'account/profile_base.html' %}
{% load staticfiles %}
{% block tab_content %}
    <div class="row">
        <div class="col-xs-12 col-md-5  padding-xs-off">
            <div class="all-alboms">
{#                <p class="albom-name">NAME</p>#}
                <div class="{% if album %}albom{% endif %}">
                    <img class="albom-ava" src="{{ user.unsorted_album_cover }}">
                    <a href="{% url 'accounts:photos' user.pk %}">Неразобранное</a>
                </div>
                {% for a in request.user.albums.all %}
                    <div class="{% if album.id != a.pk %}albom{% endif %}">
                        <img class="albom-ava"
                             src="{% if a.cover %}{{ a.cover.url }}{% else %}{{ a.images.last.image.url }}{% endif %}">
                        <a href="{% url 'accounts:photos_album' user.pk a.id %}">{{ a.name }}</a>
                    </div>
                {% endfor %}
                <div><a href="{% url 'accounts:new_album' %}" class="add-foto btn btn-default">Добавить
                    альбом</a></div>

            </div>
        </div>
        <div class="col-xs-12 col-md-7  padding-xs-off">
        {% if album != 'all' %}
            <div class="col-xs-12 options-lk padding-off options-albom  padding-xs-off">
                    {% if album and album != 'all' %}
                        <a href="{% url 'accounts:gallery_album' user.pk album.pk %}" class="blog-name-lk">{{ album.name }}</a>
                    {% else %}
                        <a href="{% url 'accounts:gallery_photo' user.pk %}" class="blog-name-lk">Неразобранное</a>
                    {% endif %}
                <div class="pull-right right-options">
                    {% if album %}
                        <form action="{% url 'accounts:album_hide' user.pk album.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="show" value="{% if album.show %}0{% else %}1{% endif %}">
                            <button type="submit"><img src="{% static "img/eye.png" %}" width="18px"></button>
                        </form>
                        {{ album.show }}
                    {% else %}
                        <form action="{% url 'accounts:photos_hide' user.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="show" value="{% if user.show_non_album_images %}0{% else %}1{% endif %}">
                            <button type="submit"><img src="{% static "img/eye.png" %}" width="18px"></button>
                        </form>
                        {{ user.show_non_album_images }}
                    {% endif %}
                    {% if album %}<a href="{% url 'accounts:album_update' user.pk album.pk %}"> <img src="{% static "img/pen.png" %}" width="15px"></a>{% endif %}
                    <a href="#"> <img src="{% static "img/dell.png" %}" width="15px"></a>
                </div>
            </div>
        {% endif %}
            <div class="all-albom-photo col-xs-12 padding-off">
                {% for image in images %}
                    {% if album == 'all' or not album %}
                        <div class="col-md-3 col-xs-6"><a href="{% url 'accounts:gallery_photo' user.pk %}?image={{ image.pk }}"><img src="{{ image.image.url }}" width="100%"></a></div>
                    {% else %}
                        <div class="col-md-3 col-xs-6"><a href="{% url 'accounts:gallery_album' user.pk image.album.pk %}?image={{ image.pk }}"><img src="{{ image.image.url }}" width="100%"></a></div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-xs-12 padding-xs-off"><a class="add-foto btn btn-default" href="{% if album and album != 'all' %}{% url 'accounts:upload_photos_album' user.pk album.pk %}{% else %}{% url 'accounts:upload_photos' user.pk %}{% endif %}">Добавить фотографии</a></div>
        </div>
    </div>
{% endblock %}

users/templates/photo/user_upload_photo.html
{% extends 'account/profile_base.html' %}
{% load staticfiles %}
{% block tab_content %}
    <form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
        {{ formset.management_form }}
        <div class="upload ">
            <div class="row"></div>
        </div>
        <div>
            <button class="btn btn-success btn-upload" type="submit">Загрузить</button>
        </div>
    </form>

    {% block additional_scripts %}
       <script src="{% static 'js/upload_form.js' %}"></script>
    {% endblock %}
{% endblock %}