bobsoccer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views
from django.views.generic import TemplateView

from users.views import ckeditor_image_upload_view, ckeditor_image_browse_view
from common.views import index

urlpatterns = [
    url(r'^users/success_signup/$', TemplateView.as_view(template_name='success_signup.html'), name='success_signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha', include('captcha.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('users.urls', namespace='accounts')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^forum/', include('talks.urls', namespace='forum')),
    url(r'^poll/', include('polls.urls', namespace='polls')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
    url(r'^payment/', include('transaction.urls', namespace='transaction')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^ckeditor/upload/$', ckeditor_image_upload_view, name='ckeditor_upload'),
    url(r'^ckeditor/browse/$', ckeditor_image_browse_view, name='ckeditor_browse'),
    url(r'^', include('common.urls', namespace='common'))
]

if settings.DEBUG:
    urlpatterns += [
            url(r'^static/(?P<path>.*)$', views.serve),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shop_view, name='base'),
    url(r'^cart/$', views.cart_view, name='cart'),
    url(r'^cart/add/$', views.ajax_cart_add, name='cart_add'),
    url(r'^cart/remove$', views.ajax_cart_remove, name='cart_remove'),
]

transaction/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.payment_view, name='payment'),
    url(r'^robokassa/$', views.result_payment_view, name='payment_result')
]

shop/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext as _


class ItemQueryset(models.QuerySet):
    def dicts(self, *args, **kwargs):
        query = self.filter(*args, **kwargs)
        return [i.as_dict() for i in query]


class Item(models.Model):
    actions = (
        ('rebuke', u'Замечание'),
        ('warning', u'Предупреждение'),
        ('ban', u'Бан')
    )

    levels = (
        (0, u'Нет'),
        (1, u'Запасной игрок'),
        (2, u'Основной игрок'),
        (3, u'Капитан'),
        (4, u'Судья'),
        (5, u'Корреспондент'),
        (6, u'Кандидат в эксперты серебро'),
        (7, u'Кандидат в эксперты золото'),
        (50, u'Эксперт'),
        (101, u'Дисквалифицированный')
    )

    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = models.TextField(verbose_name=_('Описание'),
                                   null=True, blank=True)
    image = models.ImageField(upload_to='items/',
                              verbose_name=_('Картинка'))
    price = models.PositiveIntegerField(verbose_name=_('Стоимость'), null=True,
                                        blank=True)
    level = models.PositiveSmallIntegerField(choices=levels,
                                             verbose_name=_('Минимальный уровень'))
    expired = models.PositiveSmallIntegerField(verbose_name=_('Время действия'),
                                               null=True, blank=True)
    action = models.CharField(max_length=11, choices=actions,
                              null=True, blank=True,
                              verbose_name=_('Действие предмета'))
    points = models.IntegerField(null=True, blank=True)
    admin_only = models.BooleanField(default=False, verbose_name=_('Только для администраторов?'))

    objects = ItemQueryset.as_manager()

    def __unicode__(self):
        return self.name

    def image_tag(self):
        return '<img src="%s" style="width: 150px; height: 150px;>' \
               % self.image.url

    image_tag.short_description = 'Текущая картинка'
    image_tag.allow_tags = True

    def as_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url
        }

    class Meta:
        verbose_name_plural = u'Предметы'
        verbose_name = u'Предмет'


class CartItem(models.Model):
    item = models.ForeignKey(Item, related_name='carts')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='carts')
    quantity = models.PositiveIntegerField(default=1)

shop/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, redirect

from shop.models import Item, CartItem


def shop_view(request):
    context = {
        'items': Item.objects.filter(admin_only=False)
    }
    return render(request, 'shop.html', context)


def cart_view(request):
    cart_sum = request.user.cart_sum()
    if request.method == 'POST':
        if cart_sum <= request.user.balance:
            request.user.buy_items()
            messages.add_message(request, messages.SUCCESS, 'Спасибо за покупку')
            return redirect('accounts:user_items')
        else:
            messages.add_message(request, messages.WARNING, 'Не достаточно денег на балансе.')
    if request.user.balance < cart_sum:
        balance_add = cart_sum - request.user.balance
    else:
        balance_add = None
    return render(request, 'cart.html', {'balance_add': balance_add})


@login_required
def ajax_cart_add(request):
    if request.method != 'POST' or not request.is_ajax():
        raise Http404()

    try:
        item = Item.objects.get(pk=request.POST.get('item'))
    except Item.DoesNotExist:
        return HttpResponse('ItemDoesNotExist')

    cart_item, created = CartItem.objects.get_or_create(item=item, user=request.user)
    if not created:
        cart_item.quantity += 1
        cart_item.save()

    return HttpResponse(request.user.cart_sum())


@login_required
def ajax_cart_remove(request):
    if request.method != 'POST' or not request.is_ajax():
        raise Http404()

    try:
        CartItem.objects.get(pk=request.POST.get('item')).delete()
        return HttpResponse(request.user.cart_sum())
    except CartItem.DoesNotExist:
        return HttpResponse('ItemDoesNotExist')

shop/templates/cart.html
{% extends "base_template.html" %}
{% load staticfiles %}
{% block content %}
    {% block additional_links %}
        <link rel="stylesheet" type="text/css" href="{% static "css/static_tmpl.css" %}">
    {% endblock %}

    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="pageName">
            <img class="caption" src="{% static "img/stat/ball.png" %}"/>Корзина
        </div>
        <div class="col-xs-12 basket">
            <img src="{% static "img/stat/cart.gif" %}" class="icon">
            <a href="{% url 'shop:cart' %}" class="blue" style="text-decoration:underline">
                <b>Ваша корзина:</b>
            </a>
        </div>
        {% for cart_item in request.user.carts.all %}
            <div class="col-xs-12 padding-off item">
                <div class="col-xs-6">
                    <div class="basket-product">
                        {{ cart_item.item.name }}
                        (x{{ cart_item.quantity }})
                    </div>
                    <div class="basket-price">Цена: <span>{{ cart_item.item.price }}</span></div>
                </div>
                <div class="col-xs-6">
                    <a class="btn btn-sm btn-danger item_remove" data-item="{{ cart_item.id }}">Удалить</a>
                </div>
            </div>
        {% endfor %}
        <div class="col-xs-12 borderBot">
        </div>
        <div class="col-xs-12 check-line padding-off">
            <div class="col-xs-6">
                <div>У вас на счету: <b style="color:#50B81F">{{ request.user.balance }} руб.</b><br></div>
                <div>Необходимо для оплаты: <b style="color:red"><span class="cart_sum">{{ request.user.cart_sum }}</span> руб.</b><br></div>
            </div>
            <div class="col-xs-6">
                <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Оплатить</button>
                </form>
                <form action="{% url 'transaction:payment' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="sum" value="{{ balance_add }}">
                    <button type="submit" class="btn btn-primary">Пополнить баланс</button>
                </form>
            </div>
        </div>
        <div class="col-xs-12">
            <a type="button" class="btn btn-primary to-shop" href="{% url "shop:base" %}">Вернуться в магазин</a>
        </div>
        <div class="col-xs-12 padding-off web-pay">
            <a href="http://www.megastock.ru/" target="_blank"><img src="{% static "img/stat/bil_icon_webmoney.png" %}"></a>
            &nbsp; &nbsp;
            <a href="http://money.yandex.ru/" target="_blank"><img
                    src="{% static "img/stat/bil_icon_yandex.png" %}"></a>
        </div>


    </div>
{% endblock %}
{% block additional_scripts %}
    <script>
        $('.item_remove').click(function (e) {
            e.preventDefault();
            var self = this;
            $.ajax({
                type: 'POST',
                url: '{% url 'shop:cart_remove' %}',
                data: {'item': $(self).data('item')},
                success: function (data) {
                    $(self).closest('.item').remove();
                    $('.cart_sum').html(data);
                    console.log(data)
                }
            })
        })
    </script>
{% endblock %}

shop/templates/shop.html
{% extends "base_template.html" %}
{% load staticfiles %}
{% block content %}
    {% block additional_links %}
        <link rel="stylesheet" type="text/css" href="{% static "css/static_tmpl.css" %}">
    {% endblock %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="pageName">
            <img class="caption" src="{% static "img/stat/ball.png" %}"/>Магазин подарков
        </div>
        <div class="">
            <div class="">
                <div style="float:left;width:40%">
                    <img src="{% static "img/stat/cart.gif" %}" class="icon">
                    <a href="{% url 'shop:cart' %}" class="blue" style="text-decoration:underline"><b>Ваша
                        корзина</b></a>
                    <div style="padding:5px;">У вас на счету: <b style="color:#50B81F">{{ request.user.balance }}
                        руб.</b><br></div>
                </div>
                <div style="float: left;padding-top: 5px;">
                    <button type="button" class="btn btn-lg btn-primary" href="/shop/">Пополнить баланс</button>
                </div>
            </div>
            <div class="col-xs-12 borderBot">
                <span>Доступные товары</span>
            </div>
        </div>
        {% for item in items %}
            <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9 StuffListItem2">
                <img src="{{ item.image.url }}" class="ItemImage">
                <b class="ItemTitle">{{ item.name }}</b>
                <div class="ItemDesc">
                    {{ item.description }}
                    Действует {{ item.expired }} дней.<br>
                    Минимальный уровень для использования: <b>{{ item.get_level_display }}</b>
                </div>
                <div>
                    <div class="ItemPrice">Цена: <b class="Price">{{ item.price }} руб.</b></div>
                    <img src="{% static "img/stat/cartplus.gif" %}" class="icon"><a href="" class="cart_add"
                                                                                    data-item="{{ item.pk }}"><b>Положить
                    в
                    корзину</b></a>
                </div>
            </div>
        {% endfor %}
        <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
            <a href="http://www.megastock.ru/" target="_blank"><img src="{% static "img/stat/bil_icon_webmoney.png" %}"></a>
            &nbsp; &nbsp;
            <a href="http://money.yandex.ru/" target="_blank"><img
                    src="{% static "img/stat/bil_icon_yandex.png" %}"></a>
        </div>
    </div>
{% endblock %}
{% block additional_scripts %}
    <script>
        $(document).ready(function (e) {
            $('.cart_add').click(function (e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '{% url 'shop:cart_add' %}',
                    data: {'item': $(this).data('item')},
                    success: function (data) {
                        $.notify({
                            message: 'Товар успешно добавлен в корзину.' +
                            ' К оплате:' + data + 'руб.'
                        }, {
                            type: 'success'
                        });

                        console.log(data)
                    },
                    error: function (error) {
                        console.log(error)
                    }
                })
            })
        })
    </script>
{% endblock %}