bobsoccer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views
from django.views.generic import TemplateView

from users.views import ckeditor_image_upload_view, ckeditor_image_browse_view
from common.views import index

urlpatterns = [
    url(r'^users/success_signup/$', TemplateView.as_view(template_name='success_signup.html'), name='success_signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha', include('captcha.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('users.urls', namespace='accounts')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
    url(r'^forum/', include('talks.urls', namespace='forum')),
    url(r'^poll/', include('polls.urls', namespace='polls')),
    url(r'^forecast/', include('forecast.urls', namespace='forecast')),
    url(r'^payment/', include('transaction.urls', namespace='transaction')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^ckeditor/upload/$', ckeditor_image_upload_view, name='ckeditor_upload'),
    url(r'^ckeditor/browse/$', ckeditor_image_browse_view, name='ckeditor_browse'),
    url(r'^', include('common.urls', namespace='common'))
]

if settings.DEBUG:
    urlpatterns += [
            url(r'^static/(?P<path>.*)$', views.serve),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forecast/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.forecast_view, name='forecast'),
    url(r'^create/$', views.forecast_create_view, name='competition_create'),
    url(r'^match_create/$', views.match_create, name='match_create'),
    url(r'^(?P<pk>[0-9])/result/$', views.forecast_result_view, name='forecast_result'),
    url(r'^(?P<pk>[0-9])/update/$', views.forecast_update_view, name='forecast_update'),
    url(r'^(?P<pk>[0-9])/scores/set/$', views.forecast_set_score, name='forecast_set_scores'),
    url(r'^(?P<pk>[0-9])/$', views.forecast_detail_view, name='forecast_detail'),
]

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shop_view, name='base'),
    url(r'^cart/$', views.cart_view, name='cart'),
    url(r'^cart/add/$', views.ajax_cart_add, name='cart_add'),
    url(r'^cart/remove$', views.ajax_cart_remove, name='cart_remove'),
]

forecast/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.db.models import Sum

from soccer.models import Team
from users.models import User


class Tournament(models.Model):
    name = models.CharField(max_length=255)
    date_start = models.DateField()
    date_finish = models.DateField()
    finished = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def get_users(self):
        return User.objects.filter(
            forecasts__match__in=self.matches.values_list('id')).distinct()

    def participants(self):
        return self.get_users().count()

    def update_points(self):
        self.forecast_points.all().delete()
        forecast_points = []

        for user in self.get_users():
            score = difference = result = miss = 0
            for match in self.matches.filter(finished=True):
                try:
                    forecast = match.forecasts.get(user=user)
                except Forecast.DoesNotExist:
                    continue

                team1 = match.team1_score
                team2 = match.team2_score
                team1_user = forecast.team1
                team2_user = forecast.team2
                if team1 == team1_user and team2 == team2_user:
                    score += 1
                elif team1 - team2 == team1_user - team2_user:
                    difference += 1
                elif team1 > team2 and team1_user > team2_user or \
                                        team1 < team2 and team1_user < team2_user:
                    result += 1
                else:
                    miss += 1

            total = score * 3 + difference * 2 + result
            forecast_points.append(ForecastPoint(
                user=user, tournament=self,
                score=score, difference=difference, result=result,
                miss=miss, total=total))

        ForecastPoint.objects.bulk_create(forecast_points)


class Match(models.Model):
    tournament = models.ForeignKey(Tournament, related_name='matches')
    team1 = models.ForeignKey(Team, related_name='matches_team1')
    team2 = models.ForeignKey(Team, related_name='matches_team2')
    team1_score = models.PositiveIntegerField(null=True, blank=True)
    team2_score = models.PositiveIntegerField(null=True, blank=True)
    date = models.DateField()
    time = models.TimeField()
    finished = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s vs %s' % (self.team1.name, self.team2.name)


class Forecast(models.Model):
    user = models.ForeignKey(User, related_name='forecasts')
    match = models.ForeignKey(Match, related_name='forecasts')
    team1 = models.PositiveIntegerField()
    team2 = models.PositiveIntegerField()

    def __unicode__(self):
        return '%s (%s:%s)' % (self.match.__unicode__(), self.team1, self.team2)


class ForecastPointQueryset(models.QuerySet):
    def total_scores(self):
        return self.aggregate(sum=Sum('score'))['sum']


class ForecastPoint(models.Model):
    user = models.ForeignKey(User, related_name='forecast_points')
    tournament = models.ForeignKey(Tournament, related_name='forecast_points')
    score = models.PositiveIntegerField(default=0)
    difference = models.PositiveIntegerField(default=0)
    result = models.PositiveIntegerField(default=0)
    miss = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)

forecast/forms.py
# coding=utf-8
from django import forms
from django.forms import formset_factory

from forecast.models import Match, Tournament
from soccer.models import Team


class TournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = '__all__'


class MatchForm(forms.Form):
    team1 = forms.ModelChoiceField(queryset=Team.objects.all(),
                                   required=True, label='')

    team2 = forms.ModelChoiceField(queryset=Team.objects.all(),
                                   required=True, label='')

    date = forms.DateField(label='Дата')
    time = forms.TimeField(label='Время')


class MatchScoreForm(forms.Form):
    match = forms.ModelChoiceField(queryset=Match.objects.all(),
                                   widget=forms.HiddenInput(attrs={'readonly': True}))
    team1_score = forms.IntegerField(label='', required=False)
    team2_score = forms.IntegerField(label='', required=False)


match_formset = formset_factory(MatchForm, extra=1)
match_scores_formset = formset_factory(MatchScoreForm, extra=0, can_delete=False)

forecast/views.py
from django.shortcuts import render, redirect, get_object_or_404

from forecast.forms import TournamentForm, match_formset, match_scores_formset
from forecast.models import Match, Tournament, Forecast, ForecastPoint


def forecast_view(request):
    context = {
        'tournaments': Tournament.objects.all()
    }
    return render(request, 'forecast.html', context)


def forecast_result_view(request, pk):
    tournament = get_object_or_404(Tournament, pk=pk)
    context = {
        'tournament': tournament,
        'tournaments': Tournament.objects.exclude(pk=pk),
        'points': ForecastPoint.objects.all()
    }
    return render(request, 'forecast_result.html', context)


def forecast_other_result_view(request):
    return render(request, 'forecast_result.html')


def forecast_create_view(request):
    form = TournamentForm(request.POST or None)
    formset = match_formset(request.POST or None)
    if form.is_valid() and formset.is_valid():
        tournament = form.save()

        matches = []
        for form in formset:
            matches.append(Match(
                tournament=tournament, date=form.cleaned_data.get('date'),
                time=form.cleaned_data.get('time'),
                team1=form.cleaned_data.get('team1'),
                team2=form.cleaned_data.get('team2')
            ))
        Match.objects.bulk_create(matches)
        return redirect('forecast:forecast')

    context = {
        'form': form,
        'formset': formset,
        'tournaments': Tournament.objects.all()
    }
    return render(request, 'competition_create.html', context)


def forecast_update_view(request, pk):
    obj = get_object_or_404(Tournament, pk=pk)
    form = TournamentForm(request.POST or None, instance=obj)
    formset_initial = obj.matches.values('date', 'time', 'team1', 'team2')
    formset = match_formset(request.POST or None,
                            initial=formset_initial)
    if form.is_valid() and formset.is_valid():
        tournament = form.save()

        matches = []
        for form in formset:
            if form.cleaned_data:
                try:
                    match = Match.objects.get(id=form.cleaned_data.get('id'))
                    match.date = form.cleaned_data.get('date'),
                    match.time = form.cleaned_data.get('time'),
                    match.team1 = form.cleaned_data.get('team1'),
                    match.team2 = form.cleaned_data.get('team2')
                    match.save()
                except Match.DoesNotExist:
                    matches.append(Match(
                        tournament=tournament, date=form.cleaned_data.get('date'),
                        time=form.cleaned_data.get('time'),
                        team1=form.cleaned_data.get('team1'),
                        team2=form.cleaned_data.get('team2')))

        Match.objects.bulk_create(matches)
        return redirect('forecast:forecast')

    context = {
        'form': form,
        'formset': formset,
        'tournaments': Tournament.objects.exclude(pk=obj.pk)
    }
    return render(request, 'competition_create.html', context)


def forecast_set_score(request, pk):
    tournament = get_object_or_404(Tournament, pk=pk)
    initial = [
        {'match': i, 'team1_score': i.team1_score, 'team2_score': i.team2_score} for i in tournament.matches.all()]
    formset = match_scores_formset(request.POST or None, initial=initial)
    if formset.is_valid():

        # TODO: optimize set score by moderators
        for form in formset:
            team1 = form.cleaned_data.get('team1_score')
            team2 = form.cleaned_data.get('team2_score')
            match = form.cleaned_data.get('match')
            match.team1_score = team1
            match.team2_score = team2
            match.finished = True
            match.save()

        # TODO: tournament finished
        if not tournament.matches.filter(
                team1_score__isnull=True, team2_score__isnull=True):
            tournament.finished = True
            tournament.save()
        elif tournament.finished:
            tournament.finished = False
            tournament.save()
        tournament.update_points()
    context = {
        'tournament': tournament,
        'formset': formset
    }

    return render(request, 'forecast_set_score.html', context)


def forecast_detail_view(request, pk):
    obj = get_object_or_404(Tournament, pk=pk)
    context = {
        'object': obj,
    }
    if request.method == 'POST':
        forecasts = []
        for match in obj.matches.all():
            team1 = request.POST.get('team1_%s' % match.id)
            team2 = request.POST.get('team2_%s' % match.id)
            if team1 and team2:
                try:
                    f = Forecast.objects.get(user=request.user, match=match)
                    f.team1 = team1
                    f.team2 = team2
                    f.save()
                except Forecast.DoesNotExist:
                    forecasts.append(Forecast(user=request.user, match=match,
                                              team1=team1, team2=team2))

        Forecast.objects.bulk_create(forecasts)
    return render(request, 'forecast_detail.html', context)


def match_create(request):
    return render(request, 'match_create.html')

forecast/templates/competition_create.html
{% extends "base_template.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block content-header %}
    {% include 'slider.html' %}
{% endblock %}
{% block content %}
    {% block additional_links %}
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-clockpicker.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/static_tmpl.css" %}">
    {% endblock %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna interview">
            <div class="central_column">
                <p class="caption news_caption">Конкурс прогнозов</p>
                <div class="top-link-wrap">
                    <a class="top-link" href="{% url 'forecast:competition_create' %}">Создать турнир</a>
                    <a class="top-link" href="">Турниры</a>
                    <a class="top-link" href="">Результаты прогнозов</a>
                </div>
                <div class="create-form">
                    <div class="create-form-header">
                        Новый турнир
                    </div>
                    <div class="create-form-body">
                        <form action="" method="post">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    {% bootstrap_field form.name %}
                                </div>
                                <div class="col-md-6">
                                    {% bootstrap_field form.date_start placeholder='день.мес.год' field_class='date' %}
                                </div>
                                <div class="col-md-6">
                                    {% bootstrap_field form.date_finish placeholder='день.мес.год' field_class='date' %}
                                </div>
                                <div class="col-md-12 match-formsets">
                                    <label for="">Матчи</label>
                                    {{ formset.management_form }}
                                    {% for match in formset %}
                                        <div class="form-match-wrap match-form">
                                            <div class="form-match">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        {% bootstrap_field match.team1 %}
                                                    </div>
                                                    <div class="col-md-6">
                                                        {% bootstrap_field match.team2 %}
                                                    </div>
                                                    <div class="col-md-6">
                                                        {% bootstrap_field match.date placeholder='день.мес.год' field_class='date' %}
                                                    </div>
                                                    <div class="col-md-6">
                                                        {% bootstrap_field match.time placeholder='час.мин' field_class='time' %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <a class="btn btn-primary btn-xs add_formset" href="">+ Добавить еще матч</a>
                                    </div>
                                    <button type="submit" class="btn btn-sm btn-success">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="forecast-table">
                    <table>
                        <thead>
                        <tr>
                            <th>Турниры:</th>
                            <th>Количество<br>участников</th>
                            <th>Количество<br>Матчей</th>
                            <th>Начало</th>
                            <th>Окончание</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for tournament in tournaments %}
                            <tr>
                                <td>✖ {{ tournament.name }}</td>
                                <td>{{ tournament.participants }}</td>
                                <td>{{ tournament.matches.count }}</td>
                                <td>{{ tournament.date_start }}</td>
                                <td>
                                    <div>
                                        {{ tournament.date_finish }}
                                    </div>
                                    <a class="btn-sm btn-danger" href="{% url 'forecast:forecast_update' tournament.pk %}">Редактировать</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% include "pagination.html" %}
            </div>
        </div>
    </div>

{% endblock %}
{% block additional_scripts %}
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/bootstrap-clockpicker.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.date').find('input').datepicker({
                autoclose: true,
                todayHighlight: true
            });
            $('.selectpicker').selectpicker();
            $('.time').find('input').clockpicker({
                placement: 'bottom',
                align: 'left',
                autoclose: true,
                'default': 'now'
            });
            $('.add_formset').click(function (e) {
                e.preventDefault();
                cloneMore('.match-form:last')

            });
        });

        function cloneMore(selector) {
            var newElement = $(selector).clone();
            var total_block = $('#id_form-TOTAL_FORMS');
            var total = total_block.val();
            newElement.find(':input').each(function() {
                var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });
            newElement.find('label').each(function() {
                var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
                $(this).attr('for', newFor);
            });
            total++;
            total_block.val(total);
            newElement.find('.date').find('input').datepicker({
                autoclose: true,
                todayHighlight: true
            });
            newElement.find('.time').find('input').clockpicker({
                placement: 'bottom',
                align: 'left',
                autoclose: true,
                'default': 'now'
            });
            newElement.find('.has-error').removeClass('has-error');
            newElement.find('.help-block').remove();
            newElement.find('.has-success').removeClass('has-success');
            $(selector).after(newElement);
        }
    </script>
{% endblock %}

forecast/templates/forecast.html
{% extends "base_template.html" %}
{% load staticfiles %}
{% block content-header %}
    {% include 'slider.html' %}
{% endblock %}
{% block content %}
    {% block additional_links %}
        <link rel="stylesheet" type="text/css" href="{% static "css/static_tmpl.css" %}">
    {% endblock %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna interview">
            <div class="central_column">
                <p class="caption news_caption">Конкурс прогнозов</p>
                <div class="top-link-wrap">
                    <a class="top-link" href="{% url 'forecast:competition_create' %}">Создать турнир</a>
                    <a class="top-link" href="">Турниры</a>
                    {% if tournaments %}
                        <a class="top-link" href="{% url 'forecast:forecast_result' tournaments.first.id %}">Результаты прогнозов</a>
                    {% endif %}
                </div>
                <div class="forecast-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Турниры:</th>
                                <th>Количество<br>участников</th>
                                <th>Количество<br>Матчей</th>
                                <th>Начало</th>
                                <th>Окончание</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for tournament in tournaments %}
                            <tr>
                                <td>
                                    <a href="{% url 'forecast:forecast_set_scores' tournament.id %}">установить результаты</a>
                                    <span class="hidden-title">Турнир:</span>
                                    <a href="{% url 'forecast:forecast_detail' tournament.id %}">{{ tournament.name }}</a>
                                </td>
                                <td>
                                    <span class="hidden-title">Количество участников:</span>
                                    {{ tournament.participants }}
                                </td>
                                <td>
                                    <span class="hidden-title">Количество матчей:</span>
                                    {{ tournament.matches.count }}
                                </td>
                                <td>
                                    <span class="hidden-title">Начало:</span>
                                    {{ tournament.date_start }}
                                </td>
                                <td>
                                    <div>
                                        <span class="hidden-title">Окончание:</span>
                                        {{ tournament.date_finish }}
                                    </div>
                                    <a class="btn-sm btn-danger" href="{% url 'forecast:forecast_update' tournament.pk %}">Редактировать</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% include "pagination.html" %}
            </div>
        </div>
    </div>

{% endblock %}

forecast/templates/match_create.html
{% extends "base_template.html" %}
{% load staticfiles %}
{% block content-header %}
    {% include 'slider.html' %}
{% endblock %}
{% block content %}
    {% block additional_links %}
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-clockpicker.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/static_tmpl.css" %}">
    {% endblock %}
    <div class="col-xs-12 col-sm-8 col-md-9 cold-lg-9">
        <div class="tribuna interview">
            <div class="central_column">
                <p class="caption news_caption">Результаты матчей</p>
                <div class="top-link-wrap">
                    <a class="top-link" href="#">Таблицы европейских первенств</a>
                    <a class="top-link" href="#">Лига Чемпионов</a>
                    <a class="top-link" href="#">Лига Европы</a>
                    <a class="top-link" href="#">Российская премьер-лига</a>
                </div>
                <div class="create-form">
                    <div class="create-form-header">
                        Новый матч
                    </div>
                    <div class="create-form-body">
                        <form action="">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select name="" id="" class="selectpicker" data-style="btn-white">
                                            <option value="">AC Milan</option>
                                            <option value="">AC Milan</option>
                                            <option value="">AC Milan</option>
                                            <option value="">AC Milan</option>
                                            <option value="">AC Milan</option>
                                            <option value="">AC Milan</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select name="" id="" class="selectpicker" data-style="btn-white">
                                            <option value="">ЗЕНИТ</option>
                                            <option value="">ЗЕНИТ</option>
                                            <option value="">ЗЕНИТ</option>
                                            <option value="">ЗЕНИТ</option>
                                            <option value="">ЗЕНИТ</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_tour">Тур:</label>
                                        <input id="id_tour" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_score">Счет:</label>
                                        <input id="id_score" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_start">День проведения:</label>
                                        <input type="text" class="form-control" placeholder="день.мес.год" id="id_day">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_start">Время проведения:</label>
                                        <input type="text" class="form-control" placeholder="день.мес.год" id="id_time">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-sm btn-success">Сохранить</button>
                                    <button type="button" class="btn btn-sm btn-danger">Удалить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tournament-table-wrap">
                    <div><span class="tt bold">Тур 1</span></div>
                    <div class="tournament-table">
                        <table>
                            <tbody>
                                <tr>
                                    <td><img src="{% static 'img/loko.png' %}" width="20px">Тундра</td>
                                    <td><span class="tournament-score">2 : 0</span></td>
                                    <td>Австралия<img src="{% static 'img/loko.png' %}" width="20px"></td>
                                    <td>
                                        <span class="tournament-day">03.03</span>
                                        <span class="tournament-time">15:30</span>
                                        <a class="tournament-edit" href="{% url 'forecast:match_create' %}"><i class="fa fa-wrench"></i></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block additional_scripts %}
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/bootstrap-clockpicker.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#id_start, #id_end, #id_day').datepicker({
                autoclose: true,
                todayHighlight: true
            });
            $('.selectpicker').selectpicker();
            $('#id_time').clockpicker({
                placement: 'bottom',
                align: 'left',
                autoclose: true,
                'default': 'now'
            });
        })
    </script>
{% endblock %}